// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TypeScriptDefinitionGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDtsPackageString = "d1e45432-d98b-4053-b3d7-e16d258c2959";
        public const string UIContextRuleString = "8ca1b9b9-fd6e-4a5a-a036-86da7e62912b";
        public const string guidDtsPackageCmdSetString = "cf29ca9f-817e-4ce6-baa5-5fbe652b97ce";
        public static Guid guidDtsPackage = new Guid(guidDtsPackageString);
        public static Guid UIContextRule = new Guid(UIContextRuleString);
        public static Guid guidDtsPackageCmdSet = new Guid(guidDtsPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ToggleCustomToolId = 0x0100;
    }
}
