// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TypeScriptDefinitionGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "cad7b20b-4b83-4ca6-bf24-ca36a494241c";
        public const string Name = "TypeScript Definition Generator";
        public const string Description = @"Creates and synchronizes TypeScript Definition files (d.ts) from C#/VB model classes to build strongly typed web application where the server- and client-side models are in sync. Works on all .NET project types";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "typescript, d.ts, model";
    }
}
